### ISSUE TITLE
Using skeleton.json in the add organization extension form on IBM smartcloud does not save

### ISSUE THREAD

**Issue by bgewehr** [dvdsmpsn/ibm-connect-2016-examples#1]
When i use the json definition file in the add org ext. dialog, i cannot save without error message.

Compared to a working example of surveys it seem there are lots of differences between the json files

Content of the surveys.json

```
{
    "urls":{
        "icon_url":"{webresourcesSvcRef}/web/com.ibm.form.integrations.formiwidget/images/survey_widget_icon.png",
        "url":"{webresourcesSvcRef}/web/com.ibm.form.integrations.formiwidget/Surveys.xml"
    },
    "type":"community_widget",
    "name":"Surveys",
    "description":"Surveys.desc",
    "extid":"b9a1a165-eef4-4884-bb6a-46dc71a56e5e",
    "payload":{
        "defId":"Surveys",
        "primaryWidget":"true",
        "uniqueInstance":"true",
        "loginRequired":"false",
        "themes":"wpthemeWide",
        "bundleRefId":"formiwidget",
        "itemSet":[
            {
                "value":"{communitiesSvcRef}",
                "name":"communitiesSvcRef"
            },
            {
                "value":"{version}",
                "name":"version"
            },
            {
                "value":"{webresourcesSvcRef}",
                "name":"webresourcesSvcRef"
            },
            {
                "value":"5",
                "name":"surveyNumberInOverview"
            },
            {
                "value":"/surveys",
                "name":"formSeverBaseUrl"
            },
            {
                "value":"{opensocialSvcRef}",
                "name":"opensocialSvcRef"
            },
            {
                "value":"true",
                "name":"isSC"
            }
        ],
        "url":"{webresourcesSvcRef}/web/com.ibm.form.integrations.formiwidget/Surveys.xml",
        "modes":"view edit fullpage",
        "iconUrl":"{webresourcesSvcRef}/web/com.ibm.form.integrations.formiwidget/images/survey_widget_icon.png",
        "showInPalette":"true",
        "helpLink":"{helpSvcRef}/index.jsp?topic=/com.ibm.cloud.communities.doc/community_survey_frame.html",
        "description":"Surveys.desc"
    },
    "$$hashKey":"object:22"
}
```

Is your example not intended for this use case?

**Comment by dvdsmpsn** [comment]
Hi Bernd,

The new layout of the **Organisation Extensions** screen is something which came out after I'd written the talk. I've not looked into it in depth, but can confirm that on apps.collabservnext.com, the [Connect 2016 Example App](https://github.com/dvdsmpsn/ibm-connect-2016-examples/blob/master/community-app/skeleton.json) does install correctly for my organisation with no errors.

Which server are you using? Are you attempting to install the [Connect 2016 Example App](https://github.com/dvdsmpsn/ibm-connect-2016-examples/blob/master/community-app/skeleton.json)?

What errors do you see reported in the browser console?

One more thing, you may need to check with IBM to see if Community Apps (in Organisation Extensions) have been turned on for your organisation. In the past, this was required before things would work, but I'm not sure whether this still holds true.

**Comment by bgewehr** [comment]
Believe me or not. I just tried the same again with firefox and before that i have downloaded and unzipped the zip file from github. 
This time it works well.
Only difference to my first try: I took the raw view to the clipboard and saved it with notepad++ to Extension.json. That one didn't work.
Since it works now, thank you for your attention!

**Comment by bgewehr** [comment]
Seems to be true that a single error in one extension stops the whole extension system to break. Means One fails -> no extension at all. Damned!

**Comment by bgewehr** [comment]
Do you know how long it takes for a new Community app to be shown in the add apps menu?

**Comment by bgewehr** [comment]
One more thing: When you use the json file and save the extension. The app works. When you download the json file from the extension and upload it to another one, it fails. Is there a general template working in both directions?

**Comment by dvdsmpsn** [comment]
You **must not** register the same app twice with the same `defId` twice. This will break things.

If you've done this, remove the existing app before adding a new one. If you want 2 similar apps, change the `defId` before registering the 2nd one.

For example, my template for a new community app would be this: [template.json](https://github.com/dvdsmpsn/ibm-connect-2016-examples/blob/master/community-app/template.json)

> Do you know how long it takes for a new Community app to be shown in the add apps menu?
> Wait for 5 minutes, if nothing appears, you've likely messed something up.

**Comment by bgewehr** [comment]
Thank you, your hints bring me forward step by step.
Can i build an "edit" page for some parameters (e. g. URL oder URL-Parameters) with ease or will this get too complex?
I can't find any helpful documentation out there - can you guide me?

**Comment by dvdsmpsn** [comment]
Do you mean a configuration page for your community app?

If so, then the normal menu to the right of the app title is not available. You'll have to link to your configuration page from the main page in your community app. I think that you can show/hide that based on the `canPersonalize` option in the message that IBM Connections posts into your app. If that makes sense.

**Comment by bgewehr** [comment]
Yes! We`d like to stick together some information from different systems to the whole project information page in cnx.

For that we`d like to have the project communities to have a project Id attribute which can be used in the community app urls as a parameter to call the right information.

Otherwise you'd have to configure the community apps manually to show the right things with a config page for each usage.

**Comment by dvdsmpsn** [comment]
OK, so you'll need a config link within the app and some way of persisting the data on your side.
Likely you could store the project id against the community uuid.

**Comment by bgewehr** [comment]
Yes that should work. We could store the pair  of communityID and projectID on our app side and call the right project by using that as a reference.

**Comment by bgewehr** [comment]
Is there a default mechanism for having a config page?

**Comment by dvdsmpsn** [comment]
No.

**Comment by bgewehr** [comment]
How`s that parameter canpersonalize involved?
