### ISSUE TITLE
is a generic iframe embedded experience status update possible?

### ISSUE THREAD

**Issue by bgewehr** [dvdsmpsn/ibm-connect-2016-examples#2]
I'd like to take your great code for some new stuff.

We want to build a generic status update machine which will lead back to some html code as an embedded experience.

Since pushing to the stream is quite easy, the obstacles are in that generic html iframe ee thing.

Would you thing that this is possible?
Having the open social part of the JSON POST data carrying a https://myURL payload to a generic ee iframe container?

**Comment by bgewehr** [comment]
`{
  "generator": {
    "image": { 
	"url": "https://xapps.voessing.de/selfservice.nsf/SelfServiceIcon.png?OpenFileResource"
    },
    "id": "SelfService",
    "displayName": "SelfService",
    "url": "https://xapps.voessing.de/selfservice.nsf/"
	},
  "actor": {   "id":"SelfService"
  },
  "verb": "post",
  "title": "${share}",
  "content":"",
  "updated": "2012-01-01T12:00:00.000Z",
  "object": {
    "summary": "",
    "objectType": "note",
    "id": "objectid",
    "displayName": "Das Asset EDV-106590 (TFT-LCD Monitor) des derzeitigen Besitzers Henrik Müller (IBV / IBV Hannover) erreicht am 30.06.2016 das Leasingende.",
    "url": "https://notes.voessing.de/C12564F3003E7E1C/46DFAFF010AB13E7C12579D10066E0BA/284ED47BE2BE3940C1257736004F09BD!OpenDocument"
    },
    "openSocial": {
        "embed": { 
            "gadget": "https://apps.collabservnext.com/connections/resources/web/com.ibm.social.ee.cloud/cloudee.xml", 
            "context": { 
                "customPayload": {
		"videoId": "aKdV5FvXLuI",
		"title": "DR Does Alphabet Aerobics"
		},
	    "url" : "https://cdn.rawgit.com/dvdsmpsn/ibm-connect-2016-examples/master/activity-streams/cloud-embedded-experience/ee.html",
            "debug" : true, 
            "height": 245,
            "width": 380
            }
    }
    } 
}

`

**Comment by bgewehr** [comment]
btw: how to post to a community activity stream?

**Comment by appfusions** [comment]
You could use the `customPayload` attribute to contain the HTML e.g.

```
    "openSocial": { 
        "embed": { 
            "gadget": "https://apps.collabservnext.com/connections/resources/web/com.ibm.social.ee.cloud/cloudee.xml", 
            "context": { 
                "customPayload": "<p>Hello World</p>",
                "url" : "https://path/to/your/cloud-embedded-experience/ee.html",
                "debug" : true, 
                "height": 245,
                "width": 380 
            } 
        } 
    } 
```

...then build your embedded experience html to read the `customPayload` into the DOM.

---

To post to a community activity stream, use something like this:

```
curl https://apps.collabservnext.com/connections/opensocial/basic/rest/activitystreams/urn:lsid:lconn.ibm.com:communities.community:$COMMUNITY_UUID/@all/@all \
     --user $USERNAME:$PASSWORD \
     -X POST -L -H "Content-type: application/json" \
     --data-binary @activity-01.json \
     -i -v --insecure
```

**Comment by dvdsmpsn** [comment]
Your embedded experience JavaScript would then look something like this:
https://gist.github.com/dvdsmpsn/11daf3de3ba1dbd3543bd859274eadc5

**Comment by bgewehr** [comment]
I get some errors while loading:
Unable to find widget definition for: SelfService, it will be skipped. _js:517:8
Unable to find widget definition for: iFrameAppName, it will be skipped.
<img width="233" alt="2016-04-13 18_07_42-recent updates - hpa - lokservicestelle im hafen west projektsteuerung" src="https://cloud.githubusercontent.com/assets/4056277/14500500/b45a0042-01a2-11e6-9873-d7c77cc4c5e4.png">
<img width="501" alt="2016-04-13 18_07_37-starten" src="https://cloud.githubusercontent.com/assets/4056277/14500501/b45ca78e-01a2-11e6-964d-9d69b218dc75.png">

**Comment by bgewehr** [comment]
do i need to register my app (https://notes.voessing.de) as a registered ee source url?

**Comment by bgewehr** [comment]
Now i'm this far:

`{ "generator": { 
    "image": { "url": "https://xapps.voessing.de/selfservice.nsf/SelfServiceIcon.png?OpenFileResource" }, 
    "id": "example.ee.SelfService",
    "displayName": "SelfService", 
    "url": "https://xapps.voessing.de/selfservice.nsf/" 
}, 
"actor": { 
    "id":"SelfService" }, 
"verb": "post", 
"title": "${share}", 
"content":"", "updated": "2012-01-01T12:00:00.000Z", 
"object": { 
    "summary": "", 
    "objectType": "note", 
    "id": "", 
    "displayName": "Das Asset EDV-106590 (TFT-LCD Monitor) des derzeitigen Besitzers Henrik Müller (IBV / IBV Hannover) erreicht am 30.06.2016 das Leasingende.", 
    "url": "https://notes.voessing.de/C12564F3003E7E1C/46DFAFF010AB13E7C12579D10066E0BA/284ED47BE2BE3940C1257736004F09BD!OpenDocument" 
    }, 
"openSocial": { 
    "embed": { 
        "gadget": "https://apps.collabservnext.com/connections/resources/web/com.ibm.social.ee.cloud/cloudee.xml", 
        "context": { 
            "customPayload": { 
                "url": "https://notes.voessing.de/C12564F3003E7E1C/46DFAFF010AB13E7C12579D10066E0BA/284ED47BE2BE3940C1257736004F09BD!OpenDocument",
                "title": "SelfService"
            }, 
        "url" : "https://cdn.rawgit.com/bgewehr/ibm-connect-2016-examples/master/activity-streams/cloud-embedded-experience/ee.html", 
        "debug" : true, 
        "height": 245, 
        "width": 380 
        } 
    } 
} 
}`

But the result is an empty ee div. Have to stop for today... family...
Thx so far.

**Comment by bgewehr** [comment]
Fehler:

`18:19:35.863 TypeError: _10(...) is undefined
Stack-Trace:
_5.substitute/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.gadget.layers.gadgetIncontextCommon~&exclude=dojo.main&etag=20160310.074349&lang=en&country=us:587:8
_5.substitute@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.gadget.layers.gadgetIncontextCommon~&exclude=dojo.main&etag=20160310.074349&lang=en&country=us:582:1
.createImage@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.gadget.layers.gadgetIncontextCommon~&exclude=dojo.main&etag=20160310.074349&lang=en&country=us:514:9
.generateUserImage@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:1522:8
_f.hitch/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:517:8
._showHistoryUI/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:14618:1
_10.forEach@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:664:1
._showHistoryUI@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:14598:1
._getHistoryItems/<.onComplete<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:14548:1
_f.hitch/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:517:8
.dataLoaded@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:14403:1
_f._hitchArgs/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:497:11
.handleGet@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:1998:1
_f._hitchArgs/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:497:11
._callHandlers@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:476:1
._handle@https://apps.ce.collabserv.com/connections/resources/web/_js?include=com.ibm.social.ee.gadget.Bootstrap~com.ibm.social.ee.widget.FileLoader~&exclude=dojo.main~com.ibm.social.gadget.layers.gadgetIncontextCommon&etag=20160310.074349&lang=en&country=us:471:1
_f._hitchArgs/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:497:11
_1._ioSetArgs/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:6685:8
_16@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3041:9
_14@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3023:1
_1.Deferred/this.callback@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3079:1
_16@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3050:1
_14@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3023:1
_1.Deferred/this.callback@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:3079:1
_1.xhr/<@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:6806:1
_12@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2825:9
_b@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2817:1
_11/this.resolve@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2907:1
_1a@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2863:1
_12@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2836:1
_b@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2817:1
_11/this.resolve@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2907:1
_1a@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2863:1
_12@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2843:1
_b@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2817:1
_11/this.resolve@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2907:1
_1a@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2863:1
_12@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2836:1
_b@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2817:1
_11/this.resolve@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:2907:1
_8@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:6412:1
_14@https://apps.ce.collabserv.com/connections/resources/web/_js?include=dojo.main~&etag=20160310.074349&lang=en&country=us:6429:1
1 _js:6713:1
_27() _js:6713
_1._ioSetArgs/<() _js:6689
_16() _js:3041
_14() _js:3023
_1.Deferred/this.errback() _js:3089
_16() _js:3053
_14() _js:3023
_1.Deferred/this.callback() _js:3079
_16() _js:3050
_14() _js:3023
_1.Deferred/this.callback() _js:3079
_1.xhr/<() _js:6806
_12() _js:2825
_b() _js:2817
_11/this.resolve() _js:2907
_1a() _js:2863
_12() _js:2836
_b() _js:2817
_11/this.resolve() _js:2907
_1a() _js:2863
_12() _js:2843
_b() _js:2817
_11/this.resolve() _js:2907
_1a() _js:2863
_12() _js:2836
_b() _js:2817
_11/this.resolve() _js:2907
_8() _js:6412
_14() _js:6429

`

**Comment by bgewehr** [comment]
Think I should refine the target: it is not some html code, it is a domino xpage or a domino we form I want to show in an iframe.

**Comment by bgewehr** [comment]
Damned: the whole mobile Stream is broken
![](http://i.imgur.com/I4kh7D7.jpg)

**Comment by bgewehr** [comment]
The error says "multiple errors appeared while checking"

**Comment by bgewehr** [comment]
YES!! YES!! I got it! Thank you very much!
Last thing to solve is that with using position: relative on my embed-container css our page is cut on a businesscard size. with position: inherit it is displayed full size in the pop up box.
<img width="717" alt="2016-04-14 11_46_00-homepage - updates" src="https://cloud.githubusercontent.com/assets/4056277/14524037/c4bfd7a6-0236-11e6-87a6-60661e939fa4.png">

**Comment by dvdsmpsn** [comment]
Excellent!

**Comment by bgewehr** [comment]
Having to register the ee.html as an allowed gadget in the organization extensions was missing in my first attempts.

Now i have a generic iframe embedded experience for all our xpages applications. 

GREAT.

**Comment by bgewehr** [comment]
works like a charm!
<img width="715" alt="2016-04-14 12_09_51-neue benachrichtigung" src="https://cloud.githubusercontent.com/assets/4056277/14524692/e100e362-0239-11e6-90a6-8904203ab4c6.png">

**Comment by bgewehr** [comment]
One thing left: Since the new activity feed events cause my mobile app stream to be broken, how can i delete them? The standard REST DELETE call did nothing but 401 errors. Any suggestions?

**Comment by dvdsmpsn** [comment]
Sending REST calls to the application _really shouldn't_ break it. If the standard REST DELETE call didn't work, I'd recommend taking this up with IBM. They need to be aware of the problem.
